# lore 格式: 饱食度: 1000
检测关键字: "饱食度"

# 补充一次饱食度消耗的数量, 例如饱食度: 1000, 补充一次变为饱食度: 980
消耗饱食度: 20

# 饥饿惩罚功能
饥饿惩罚:
  开启: false
  # 当玩家饥饿值低于设定值时, 禁止玩家攻击或破坏方块
  检测值: 20
  禁止攻击: false
  禁止破坏方块: false

提示消息:
  禁止破坏方块: "你太累了不能破坏任何方块"
  禁止攻击: "你不能攻击任何玩家"